# Component Labels (Blue: #0052CC)
- name: "component:agent-spec-analyst"
  description: "Issues related to specification analysis agent"
  color: "0052CC"

- name: "component:agent-test-designer"
  description: "Issues related to test design agent"
  color: "0052CC"

- name: "component:agent-arch-designer"
  description: "Issues related to architecture design agent"
  color: "0052CC"

- name: "component:agent-impl-specialist"
  description: "Issues related to implementation specialist agent"
  color: "0052CC"

- name: "component:agent-qa-validator"
  description: "Issues related to QA validation agent"
  color: "0052CC"

- name: "component:command-spec-init"
  description: "Issues related to spec initialization command"
  color: "0052CC"

- name: "component:command-spec-review"
  description: "Issues related to spec review command"
  color: "0052CC"

- name: "component:command-impl-plan"
  description: "Issues related to implementation planning command"
  color: "0052CC"

- name: "component:command-qa-check"
  description: "Issues related to QA check command"
  color: "0052CC"

- name: "component:command-spec-workflow"
  description: "Issues related to complete workflow command"
  color: "0052CC"

- name: "component:installation"
  description: "Issues related to framework installation"
  color: "0052CC"

- name: "component:validation"
  description: "Issues related to framework validation"
  color: "0052CC"

- name: "component:docs"
  description: "Issues related to documentation"
  color: "0052CC"

# Type Labels
- name: "type:bug"
  description: "Software defects and errors"
  color: "D73A49"

- name: "type:enhancement"
  description: "New features and improvements"
  color: "A2EEEF"

- name: "type:question"
  description: "Support and usage questions"
  color: "D876E3"

- name: "type:documentation"
  description: "Documentation improvements"
  color: "0075CA"

- name: "type:security"
  description: "Security-related issues"
  color: "F85149"

# Priority Labels
- name: "priority:critical"
  description: "System-breaking issues requiring immediate attention"
  color: "B60205"

- name: "priority:high"
  description: "Important features or serious bugs"
  color: "D93F0B"

- name: "priority:normal"
  description: "Standard priority items"
  color: "FBCA04"

- name: "priority:low"
  description: "Nice-to-have improvements"
  color: "0E8A16"

# Status Labels
- name: "status:needs-triage"
  description: "New issues requiring review and classification"
  color: "FBCA04"

- name: "status:good-first-issue"
  description: "Beginner-friendly issues for new contributors"
  color: "7057FF"

- name: "status:help-wanted"
  description: "Issues seeking community contributions"
  color: "008672"

- name: "status:blocked"
  description: "Issues waiting on dependencies or external factors"
  color: "D93F0B"

- name: "status:in-progress"
  description: "Issues currently being worked on"
  color: "0E8A16"

- name: "status:needs-info"
  description: "Issues requiring additional information from reporter"
  color: "F9D71C"

- name: "status:validated"
  description: "Issues validated by framework validation checks"
  color: "0E8A16"

- name: "status:validation-failed"
  description: "Issues where framework validation checks failed"
  color: "D93F0B"