name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug] "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide the essential information below.
  
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Clear description of the bug and what you expected instead
      placeholder: Describe what went wrong and what should have happened...
    validations:
      required: true
  
  - type: textarea
    id: steps
    attributes:
      label: How to reproduce
      description: Steps to reproduce the issue
      placeholder: |
        1. Run command: ./scripts/install.sh
        2. Try to use: /csf:spec
        3. Error occurs: ...
    validations:
      required: true
  
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part has the issue?
      options:
        - "Installation"
        - "Agent: csf-spec"
        - "Agent: csf-implement" 
        - "Agent: csf-document"
        - "Command: /csf:spec"
        - "Command: /csf:implement"
        - "Command: /csf:document"
        - "Command: /csf:workflow"
        - "Validation script"
        - "Other"
    validations:
      required: true
  
  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: "macOS 13, Claude Code v1.0.0"
    validations:
      required: true