name: Documentation Improvement
description: Suggest improvements to documentation
title: "[Docs] "
labels: ["type:documentation", "status:good-first-issue"]
assignees: []
body:
  - type: dropdown
    id: doc-section
    attributes:
      label: Documentation Section
      description: Which documentation needs improvement?
      options:
        - "README.md"
        - "Installation Guide"
        - "Agent Documentation"
        - "Command Documentation"
        - "Examples and Tutorials"
        - "Troubleshooting Guide"
        - "API Documentation"
        - "Contributing Guidelines"
        - "Other"
    validations:
      required: true
  
  - type: input
    id: doc-file
    attributes:
      label: Specific File
      description: If known, what specific file needs improvement?
      placeholder: "e.g., framework/agents/spec-analyst.md"
  
  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: What is unclear, missing, or incorrect in the current documentation?
      placeholder: Describe what needs to be improved...
    validations:
      required: true
  
  - type: textarea
    id: proposed-improvement
    attributes:
      label: Proposed Improvement
      description: How would you improve this documentation?
      placeholder: |
        Suggest specific changes such as:
        - Add section about...
        - Clarify explanation of...
        - Include example for...
        - Fix incorrect information about...
    validations:
      required: true
  
  - type: textarea
    id: user-impact
    attributes:
      label: User Impact
      description: Who would benefit from this improvement and how?
      placeholder: |
        This would help:
        - New users who...
        - Experienced users when...
        - Contributors working on...
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: Add any other context about the documentation improvement...