name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature] "
labels: ["type:enhancement", "status:needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please provide detailed information to help us understand and evaluate your request.
  
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature in detail...
    validations:
      required: true
  
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the specific use case and how this feature would be used
      placeholder: |
        As a [type of user], I want [functionality] so that [benefit/goal].
        
        Specific scenario:
        1. I am working on...
        2. I need to...
        3. Currently I have to...
        4. With this feature I could...
    validations:
      required: true
  
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What specific, measurable criteria would indicate this feature is complete?
      placeholder: |
        - [ ] Criteria 1: The system should...
        - [ ] Criteria 2: Users can...
        - [ ] Criteria 3: The feature should handle...
    validations:
      required: true
  
  - type: dropdown
    id: component
    attributes:
      label: Framework Component
      description: Which component would this feature primarily affect?
      options:
        - "New Agent"
        - "New Command"
        - "Agent: Spec Analyst"
        - "Agent: Test Designer"
        - "Agent: Arch Designer"
        - "Agent: Impl Specialist"
        - "Agent: QA Validator"
        - "Command: /spec-init"
        - "Command: /spec-review"
        - "Command: /impl-plan"
        - "Command: /qa-check"
        - "Command: /spec-workflow"
        - "Installation System"
        - "Validation System"
        - "Documentation"
        - "Core Framework"
    validations:
      required: true
  
  - type: dropdown
    id: priority
    attributes:
      label: Business Priority
      description: How important is this feature to your workflow?
      options:
        - "Critical - Blocking current work"
        - "High - Significantly improves productivity"
        - "Medium - Nice to have improvement"
        - "Low - Minor convenience feature"
    validations:
      required: true
  
  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas
      description: Do you have any ideas about how this could be implemented?
      placeholder: Share any technical approaches, examples from other tools, or implementation suggestions...
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered or tried?
      placeholder: Describe any workarounds, alternative tools, or different approaches you've considered...
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples
      placeholder: Add any other context about the feature request here...