name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature] "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you'd like to see added.
  
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: What feature would you like to see?
      placeholder: Describe the feature you'd like added...
    validations:
      required: true
  
  - type: textarea
    id: use-case
    attributes:
      label: Why do you need this?
      description: What problem would this solve for you?
      placeholder: |
        I want to... but currently I have to...
        This would help me...
    validations:
      required: true
  
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part would this affect?
      options:
        - "New Agent"
        - "New Command"
        - "Agent: csf-spec"
        - "Agent: csf-implement"
        - "Agent: csf-document"
        - "Command: /csf:spec"
        - "Command: /csf:implement"
        - "Command: /csf:document"
        - "Command: /csf:workflow"
        - "Installation"
        - "Validation"
        - "Core Framework"
    validations:
      required: true