name: Installation Question
description: Get help with framework installation issues
title: "[Installation] "
labels: ["type:question", "component:installation"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Before asking your question, please check:
        - [Installation Documentation](../README.md#installation)
        - [Troubleshooting Guide](../docs/troubleshooting.md)
        - [Existing Installation Issues](../../issues?q=is%3Aissue+label%3Acomponent%3Ainstallation)
  
  - type: checkboxes
    id: troubleshooting
    attributes:
      label: Troubleshooting Checklist
      description: Please confirm you have tried these steps
      options:
        - label: I have admin/sudo access on my system
        - label: I have verified my shell is supported (bash, zsh, fish)
        - label: I have checked file permissions in ~/.claude directory
        - label: I have tried running the installation script with verbose output
        - label: I have reviewed the installation script for obvious errors
  
  - type: textarea
    id: question
    attributes:
      label: Installation Question
      description: What specific installation issue are you experiencing?
      placeholder: Describe your installation question or problem...
    validations:
      required: true
  
  - type: textarea
    id: attempted-solutions
    attributes:
      label: Attempted Solutions
      description: What have you already tried?
      placeholder: |
        - Tried solution 1...
        - Attempted solution 2...
        - Searched for...
    validations:
      required: true
  
  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "e.g., macOS 13.0, Ubuntu 22.04, Windows 11"
    validations:
      required: true
  
  - type: input
    id: shell
    attributes:
      label: Shell
      placeholder: "e.g., bash, zsh, fish"
    validations:
      required: true
  
  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: Please paste any error messages or unexpected output
      placeholder: Paste error messages here...
      render: shell
  
  - type: textarea
    id: installation-command
    attributes:
      label: Installation Command Used
      description: What exact command did you run?
      placeholder: "e.g., curl -sSL https://raw.githubusercontent.com/..."
      render: shell