name: Issue Validation

on:
  issues:
    types: [opened, edited]

jobs:
  validate-framework-issue:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: contains(github.event.issue.labels.*.name, 'component:validation') || contains(github.event.issue.labels.*.name, 'component:installation')
    permissions:
      issues: write
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Run framework validation
        id: validation
        run: |
          # Check if validation script exists
          if [[ ! -f "framework/validate-framework.sh" ]]; then
            echo "validation_status=no_script" >> $GITHUB_OUTPUT
            echo "Validation script not found" > validation_output.txt
            exit 0
          fi
          
          # Make script executable
          chmod +x framework/validate-framework.sh
          
          # Run validation and capture output
          if ./framework/validate-framework.sh > validation_output.txt 2>&1; then
            echo "validation_status=success" >> $GITHUB_OUTPUT
          else
            echo "validation_status=failure" >> $GITHUB_OUTPUT
          fi
      
      - name: Post validation results
        uses: actions/github-script@v7
        with:
          script: |
            try {
              const fs = require('fs');
              let validationOutput = '';
              
              try {
                validationOutput = fs.readFileSync('validation_output.txt', 'utf8');
              } catch (error) {
                validationOutput = 'No validation output available';
              }
              
              const status = '${{ steps.validation.outputs.validation_status }}';
              
              let message = '';
              const labelsToAdd = [];
              
              if (status === 'success') {
                message = [
                  '✅ **Framework Validation Passed**',
                  '',
                  'The framework validation checks have completed successfully. The reported issue may be environment-specific or require additional investigation.',
                  '',
                  '<details>',
                  '<summary>Validation Output</summary>',
                  '',
                  '```',
                  validationOutput,
                  '```',
                  '</details>',
                  '',
                  '### Next Steps',
                  '- Please verify your local environment matches the validation requirements',
                  '- Check if the issue persists with a fresh installation',
                  '- Provide additional environment details if the problem continues'
                ].join('\\n');

                labelsToAdd.push('status:validated');
                
              } else if (status === 'failure') {
                message = [
                  '❌ **Framework Validation Failed**',
                  '',
                  'The framework validation checks have identified issues that may be related to your report.',
                  '',
                  '<details>',
                  '<summary>Validation Output</summary>',
                  '',
                  '```',
                  validationOutput,
                  '```',
                  '</details>',
                  '',
                  '### Action Required',
                  'This validation failure indicates potential framework issues that need to be addressed. A maintainer will investigate and provide guidance.'
                ].join('\\n');

                labelsToAdd.push('status:validation-failed');
                labelsToAdd.push('priority:high'); // Validation failures are high priority
                
              } else if (status === 'no_script') {
                message = [
                  'ℹ️ **Framework Validation Not Available**',
                  '',
                  'The framework validation script is not available in this repository. Manual investigation will be required.',
                  '',
                  '### Manual Validation Required',
                  'A maintainer will manually review your issue and provide assistance.'
                ].join('\\n');

                // No status labels for this case
              }
              
              // Add status labels
              if (labelsToAdd.length > 0) {
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  labels: labelsToAdd
                });
              }
              
              // Post comment with validation results
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: message
              });
              
              console.log(\`Posted validation results for issue #\${context.issue.number}: \${status}\`);
              
            } catch (error) {
              console.error('Failed to post validation results:', error);
              
              // Post error message
              const errorMessage = [
                '⚠️ **Validation Error**',
                '',
                'There was an error running the framework validation. A maintainer will manually review your issue.',
                '',
                \`Error: \${error.message}\`
              ].join('\\n');

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: errorMessage
              });
            }