name: Validate Framework

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validate Framework Structure and Configuration
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Run comprehensive framework validation
      run: |
        echo "🔍 Running comprehensive framework validation..."
        
        # Run validation directly from repository (preserves repository mode)
        chmod +x framework/validate-framework.sh
        ./framework/validate-framework.sh
    
    - name: Verify installation scripts
      run: |
        echo "📋 Verifying installation scripts..."
        
        # Check script existence
        for script in install.sh update.sh uninstall.sh; do
          if [ -f "scripts/$script" ]; then
            echo "✅ scripts/$script exists"
          else
            echo "❌ scripts/$script missing"
            exit 1
          fi
        done
        
        # Check script permissions
        for script in install.sh update.sh uninstall.sh; do
          if [ -x "scripts/$script" ]; then
            echo "✅ scripts/$script is executable"
          else
            echo "❌ scripts/$script not executable"
            exit 1
          fi
        done
        
        echo "✅ All installation scripts validated"